name: Kwiki-PageInclude
version: 0.02
abstract: Include other page into this one.
author: Kang-min Liu <gugod@gugod.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  Spiffy: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
